version: "2.4"
services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test123
    volumes:
    - ./db:/var/lib/mysql

  app:
    build: ./
    depends_on:
      - db
    ports:
      - 80:80